import "context.dart";
import "typed_statements.dart";

enum PostStatementAction { continueProgram, endProgram }

/// Interpreter for a simple BASIC-like programming language.
///
/// This interpreter parses and executes a list of statements, managing [_context]
/// and program flow.
class Interpreter {
  /// A map storing the current values of variables.
  final Context _context = Context();

  /// Creates a new interpreter instance
  Interpreter();

  /// Interprets the given program [Statement]s.
  ///
  /// Parses the code into a list of statements and then executes them line by line, according to the line numbers specified in the code.
  ///
  /// The interpreter maintains its state after the function is executed. It can be used to interpret multiple programs or used in a REPL environment.
  ///
  /// Returns a list of strings, where each string is the output generated by PRINT statements.
  /// Throws an [Exception] if the parser does not find any statements.
  List<String> interpret(List<TypedStatement> statements) {
    final List<String> outputLines = [];
    final int initialStatementIndex = _context.getStatementCount();
    while (_context.getStatementCount() - initialStatementIndex <
        statements.length) {
      TypedStatement statement =
          statements[_context.getStatementCount() - initialStatementIndex];

      final postStatementAction = _executeStatement(statement, outputLines);

      if (postStatementAction == PostStatementAction.endProgram) {
        break;
      }

      _context.incrementStatementCount();
    }

    return outputLines;
  }

  /// Resets the execution context of the interpreter.
  ///
  /// * Resets the current statement index to 0.
  /// * Removes all variables from the context.
  /// * Removes all functions from the context.
  void resetContext() {
    _context.reset();
  }

  /// Executes a statement.
  PostStatementAction _executeStatement(
    TypedStatement statement,
    List<String> outputLines,
  ) {
    /// IF
    if (statement is TypedIfStatement) {
      TypedStatement? thenStatement = statement.execute(_context);
      if (thenStatement != null) {
        _executeStatement(thenStatement, outputLines);
      }
      return PostStatementAction.continueProgram;

      /// END
    } else if (statement is TypedEndStatement) {
      return PostStatementAction.endProgram;

      /// PRINT
    } else if (statement is TypedPrintStatement) {
      String output = statement.execute(_context);
      outputLines.add(output);
      return PostStatementAction.continueProgram;

      /// FOR
    } else if (statement is TypedForStatement) {
      final startValue = statement.start.evaluate(_context);
      final endValue = statement.end.evaluate(_context);
      final stepValue = statement.step.evaluate(_context);
      for (
        var i = startValue;
        stepValue > 0 ? i <= endValue : i >= endValue;
        i += stepValue
      ) {
        _context.declareVariable(statement.loopVariableName, i);
        _executeStatement(statement.body, outputLines);
      }
      return PostStatementAction.continueProgram;

      /// FUNCTION
    } else if (statement is TypedFunctionDeclarationStatement) {
      statement.execute(_context);
      return PostStatementAction.continueProgram;

      /// LET
    } else if (statement is TypedLetStatement) {
      statement.execute(_context);
      return PostStatementAction.continueProgram;

      /// REM
    } else if (statement is TypedRemarkStatement) {
      return PostStatementAction.continueProgram;

      /// Unknown statement
    } else {
      throw Exception("Unsupported statement type: $statement");
    }
  }
}
