import "statements.dart";
import "context.dart";

enum PostStatementAction { continueProgram, endProgram }

/// Interpreter for a simple BASIC-like programming language.
///
/// This interpreter parses and executes a list of statements, managing [context]
/// and program flow.
class Interpreter {
  /// A map storing the current values of variables.
  final Context context = Context();

  /// A list of PRINT statement outputs.
  final List<String> outputLines = [];

  /// Creates a new interpreter instance
  Interpreter();

  /// Interprets the given program [Statement]s.
  ///
  /// Parses the code into a list of statements and then executes them line by line, according to the line numbers specified in the code.
  ///
  /// Returns a list of strings, where each string is the output generated by PRINT statements.
  /// Throws an [Exception] if the parser does not find any statements.
  List<String> interpret(List<Statement> statements) {
    while (context.statementIndex < statements.length) {
      Statement statement = statements[context.statementIndex];

      final postStatementAction = executeStatement(statement);

      if (postStatementAction == PostStatementAction.endProgram) {
        break;
      }

      context.statementIndex++;
    }

    return outputLines;
  }

  /// Resets the execution context of the interpreter.
  ///
  /// * Resets the current statement index to 0.
  /// * Removes all variables from the context.
  void resetContext() {
    context.reset();
  }

  /// Executes a statement.
  PostStatementAction executeStatement(Statement statement) {
    /// IF
    if (statement is IfStatement) {
      Statement? thenStatement = statement.execute(context);
      if (thenStatement != null) {
        executeStatement(thenStatement);
      }
      return PostStatementAction.continueProgram;

      /// END
    } else if (statement is EndStatement) {
      return PostStatementAction.endProgram;

      /// PRINT
    } else if (statement is PrintStatement) {
      String output = statement.execute(context);
      outputLines.add(output);
      return PostStatementAction.continueProgram;

      /// LET
    } else if (statement is LetStatement) {
      statement.execute(context);
      return PostStatementAction.continueProgram;

      /// REM
    } else if (statement is RemarkStatement) {
      return PostStatementAction.continueProgram;

      /// Unknown statement
    } else {
      throw Exception("Unsupported statement type: $statement");
    }
  }
}
